config/routes.rb
Rails.application.routes.draw do
  get 'users' => 'users#index'
  get 'users/new' => 'users#new'
  post 'users/create' => 'users#create'
  get 'users/:id/edit' => 'users#edit'
  patch 'users/:id' => 'users#update'
  get 'users/:id' => 'users#show'
  delete 'users/:id' => 'users#destroy'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :first_name, :last_name, :email_address, presence: true
  validates :email_address, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  end

  def create
  	@user = User.new(user_params)
		if @user.valid?
			@user.save
			flash[:success] = "You are saved in the system"
      redirect_to '/users'
		else
      flash[:errors] = @user.errors.full_messages
      puts @user.errors.full_messages
			redirect_to '/users/new'
		end  
  end

  def show
    @user = User.find(params[:id])
  end

  #renders edit page
  def edit
    @user = User.find(params[:id])
  end

  def update
    puts params
    @user = User.update(User.find(params[:id]),user_params)
    
    puts @user 
    if @user.valid?

      flash[:success] = "Updated successfully in the system"
      redirect_to '/users'
    else
      flash[:errors] = @user.errors.full_messages
      puts @user.errors.full_messages
      redirect_to "/users/#{params[:id]}/edit"
    end
  end

  def destroy
    User.destroy(params[:id])
    redirect_to '/users'
  end

  private
  def user_params
    params.require(:user).permit(:first_name,:last_name,:email_address,:password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<html lang="en">
	<head>
	    <title>Edit</title>
	</head>
	<body>
		<% if flash[:errors] %>
			<% flash[:errors].each do |e| %>
				<p><%= e %></p>
			<% end %>
		<% end %>
		<h1>Editing User</h1>
		<!-- <form action='/users' method='post'> -->
		<form action='/users/<%= @user.id %>'method='post'>
			<!-- hidden HTTP patch request -->
			<input type="hidden" name="_method" value="patch">
			<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
			<p>First Name: <input type='text' value="<%= @user.first_name %>" name='user[first_name]'></p>
			<p>Last Name: <input type='text' value="<%= @user.last_name %>" name='user[last_name]'></p>
			<p>Email: <input type='text' value="<%= @user.email_address %>" name='user[email_address]'></p>
			<p>Password: <input type='password' name='password'></p>
			<p><input type='submit' value='Update'></p>
		</form>
		<a href="/users/<%= @user.id %>">Show</a>
		<a href="#" onclick="history.go(-1)">Back</a>
	</body>
</html>

app/views/users/index.html.erb
<html lang="en">
	<head>
	    <title>User Management</title>
	</head>
	<body>
		<h1>Listing Users</h1>
		<table>
			<th>
				<tr>
					<td>First Name</td>
					<td>Last Name</td>
					<td>Email</td>
					<td></td>
				</tr>
			</th>

			<% @users.each do |user| %>
				<tr>
					<td><%= user.first_name %></td>
					<td><%= user.last_name %></td>	
					<td><%= user.email_address %></td>	
					<td><a href="users/<%= user.id %>">Show</a> <a href="users/<%= user.id %>/edit">Edit</a> <a href="/users/<%= user.id %>" data-method='delete'>Destroy</a></td>	
				</tr>
			<% end %>
		</table><br>
		<a href="users/new">New User</a>
	</body>
</html>
	   

app/views/users/new.html.erb
<html lang="en">
	<head>
	    <title>New</title>
	</head>
	<body>
		<% if flash[:errors] %>
			<% flash[:errors].each do |e| %>
				<p><%= e %></p>
			<% end %>
		<% end %>

		<h1>New User</h1>
		<!-- <form action='/users' method='post'> -->
		<form action='<%= users_create_path %>' method='post'>
			<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
			<p>First Name: <input type='text' name='user[first_name]'></p>
			<p>Last Name: <input type='text'name='user[last_name]'></p>
			<p>Email: <input type='text' name='user[email_address]'></p>
			<p>Password: <input type='password' name='user[password]'></p>
			<p><input type='submit' value='Create'></p>
		</form>

		<a href="#" onclick="history.go(-1)">Back</a>
	</body>
</html>

app/views/users/show.html.erb
<html lang="en">
	<head>
	    <title>New</title>
	</head>
	<body>
			<p>First Name: <%= @user.first_name %></p>
			<p>Last Name: <%= @user.last_name %></p>
			<p>Email: <%= @user.email_address %></p>
			<a href="/users/<%= @user.id %>/edit">Edit</a>
			<a href="<%= users_path %>">Back</a>
	</body>
</html>
	